-- ===========================================================================
-- GENERATED — do not edit by hand. Exported from the editor's live part defs
-- (CareerDB.PartPrice: def.CostOf(mat) with TechFloor applied). The mat set
-- per part is the distinct image of EffectiveMat over MatDB.Order, so a
-- pinned part (wheel→Rubber, gusset→Steel) emits exactly its pinned mat.
-- Exported 2026-08-13. Regenerate via the bridge command noted in
-- docs/Server_Economy_Design_2026-08-13.md whenever a part, price, material
-- or TechFloor changes. rosterOnly parts and the core are excluded: the shop
-- never sells them.
-- ===========================================================================
BEGIN;
INSERT INTO part_prices (part_id, mat, price) VALUES
    ('cube', 'ABS', 7),
    ('cube', 'Aluminum', 37),
    ('cube', 'Steel', 87),
    ('cube', 'Titanium', 187),
    ('cube', 'CarbonFiber', 88),
    ('cube', 'Tungsten', 1601),
    ('beam', 'ABS', 13),
    ('beam', 'Aluminum', 65),
    ('beam', 'Steel', 151),
    ('beam', 'Titanium', 325),
    ('beam', 'CarbonFiber', 154),
    ('beam', 'Tungsten', 2779),
    ('beamlong', 'ABS', 21),
    ('beamlong', 'Aluminum', 108),
    ('beamlong', 'Steel', 251),
    ('beamlong', 'Titanium', 541),
    ('beamlong', 'CarbonFiber', 256),
    ('beamlong', 'Tungsten', 4632),
    ('plate', 'ABS', 8),
    ('plate', 'Aluminum', 40),
    ('plate', 'Steel', 94),
    ('plate', 'Titanium', 203),
    ('plate', 'CarbonFiber', 96),
    ('plate', 'Tungsten', 1737),
    ('gusset', 'Steel', 200),
    ('engine', 'Aluminum', 106),
    ('engine', 'Steel', 247),
    ('engine', 'Titanium', 533),
    ('battery', 'Aluminum', 120),
    ('wheel', 'Rubber', 60),
    ('spinner', 'ABS', 5),
    ('spinner', 'Aluminum', 26),
    ('spinner', 'Steel', 61),
    ('spinner', 'Titanium', 131),
    ('spinner', 'CarbonFiber', 62),
    ('spinner', 'Tungsten', 1118),
    ('spike', 'ABS', 4),
    ('spike', 'Aluminum', 20),
    ('spike', 'Steel', 46),
    ('spike', 'Titanium', 98),
    ('spike', 'CarbonFiber', 46),
    ('spike', 'Tungsten', 841),
    ('pivot', 'ABS', 150),
    ('pivot', 'Aluminum', 150),
    ('pivot', 'Steel', 150),
    ('pivot', 'Titanium', 183),
    ('pivot', 'CarbonFiber', 150),
    ('pivot', 'Tungsten', 1563),
    ('spindle', 'ABS', 150),
    ('spindle', 'Aluminum', 150),
    ('spindle', 'Steel', 150),
    ('spindle', 'Titanium', 183),
    ('spindle', 'CarbonFiber', 150),
    ('spindle', 'Tungsten', 1563),
    ('ram', 'ABS', 150),
    ('ram', 'Aluminum', 150),
    ('ram', 'Steel', 150),
    ('ram', 'Titanium', 183),
    ('ram', 'CarbonFiber', 150),
    ('ram', 'Tungsten', 1563),
    ('blade', 'ABS', 1),
    ('blade', 'Aluminum', 4),
    ('blade', 'Steel', 9),
    ('blade', 'Titanium', 20),
    ('blade', 'CarbonFiber', 10),
    ('blade', 'Tungsten', 174),
    ('wedge', 'ABS', 6),
    ('wedge', 'Aluminum', 28),
    ('wedge', 'Steel', 66),
    ('wedge', 'Titanium', 142),
    ('wedge', 'CarbonFiber', 67),
    ('wedge', 'Tungsten', 1216),
    ('hook', 'ABS', 3),
    ('hook', 'Aluminum', 13),
    ('hook', 'Steel', 30),
    ('hook', 'Titanium', 65),
    ('hook', 'CarbonFiber', 31),
    ('hook', 'Tungsten', 556),
    ('rangefinder', 'Aluminum', 120),
    ('compass', 'Aluminum', 180),
    ('tiltsensor', 'Aluminum', 60),
    ('wallsensor', 'Aluminum', 90),
    ('trapsensor', 'Aluminum', 70),
    ('dmgbus', 'Aluminum', 70);
INSERT INTO schema_version (version) VALUES (11);
COMMIT;
